# Default values for vbump.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maibornwolff/vbump
  tag: 1.1.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
  tls: []

nodeSelector: {}

tolerations: []

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Mi

resources:
  limits:
   cpu: 100m
   memory: 20Mi
  requests:
   cpu: 100m
   memory: 2Mi
